### PR TITLE
Dont use node-fetch

### LINKED ISSUE #206: Support for proxy
Hi,

are the proxy environment variables supported when uploading the assets for the release?

I'm getting the following error and I'm an environment that uses an http/https proxy.
```
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag v0.10...
⬆️ Uploading myhello-v0.10_debug.zip...
⬆️ Uploading myhello-v0.10_release.zip...
Error: request to https://uploads.github.com/[redacted][7](https://github.com/[redacted]?check_suite_focus=true#step:8:7)41[8](https://github.com/[redacted]?check_suite_focus=true#step:8:8)2/assets?name=myhello-v0.[10](https://github.com/[redacted]?check_suite_focus=true#step:8:10)_debug.zip failed, reason: connect ETIMEDOUT 140.82.112.13:443
```

The release is created fine though, but the assets are missing.

### PR DESCRIPTION
**Pull request by timor-raiman**
closes #206

### CODE REVIEW

File: src/github.ts [hunk 1]
```diff
@@ -159,16 +158,17 @@ export const upload = async (
   console.log(`⬆️ Uploading ${name}...`);
   const endpoint = new URL(url);
   endpoint.searchParams.append("name", name);
-  const resp = await fetch(endpoint, {
+  const resp = await github.request({
```
Comment (softprops) [inline src/github.ts:161]: TIL. nice

**Comment by softprops** [comment]
this should be available in the new v2 tag
