### PR TITLE
Don't swallow errors

### LINKED ISSUE #383: The action should fail with an error if the `files:` settings are not valid
Example: https://github.com/rpdelaney/downforeveryone/actions/runs/6149726050/job/16686210047

```
🤔 dist/downforeveryone*.whl,dist/downforeveryone*.tar.gz not include valid file.
```

Instead of simply failing, this workflow run instead published a release with all the files in the repo: https://github.com/rpdelaney/downforeveryone/releases/tag/v1.0.5

This is a significant issue because it hides the fact that the action is not doing what the user expected and ends with success. The warnings are buried in the folds so I did not discover the problem until the release archive was already out there and downloaded.

### PR DESCRIPTION
**Pull request by rpdelaney**
- Change 'pattern does not match any files' warning to fatal
- Also raise a fatal error if the config file is not valid

Closes #383

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ async function run() {
     if (config.input_files) {
       const patterns = unmatchedPatterns(config.input_files);
       patterns.forEach((pattern) =>
-        console.warn(`🤔 Pattern '${pattern}' does not match any files.`)
+        throw new Error(`⚠️  Pattern '${pattern}' does not match any files.`)
```
Comment (softprops) [inline src/main.ts:28]: makes sense to me. thanks @rpdelaney

**Comment by softprops** [comment]
this should be available in the new v2 tag
